### ISSUE TITLE
Longer sounds

### ISSUE THREAD

**Issue by iurienistor** [iurie-sw/geonkick#115]
Longer sounds, now is 4 seconds... maybe 7?.. https://github.com/iurie-sw/geonkick/issues/107

**Comment by Tremeschin** [comment]
> Yes, thought about this, I'll try to make it longer... The problem with longer sounds it means it requires more processing and this slows down the real-time visualization and audition when someone modifies the parameter (created #115).

Could there be a realtime visualization toggle button to bypass this technical issue?

ie, update the internal sample only when an action is finished like dragging an envelope point or hold drag knobs?

**Comment by iurienistor** [comment]
I have encreased to 20 seconds, everyhting works ok. The only problem is the amount of memory that will take Geonkick instance.

**Comment by Tremeschin** [comment]
How much memory we're taking about here? I've some pretty big projects and I never used more than 20 geonkick instances, though only one sample per instance as I don't use kits so I'm guessing this won't be a nightmare comparing 4s -> 20s...?

**Comment by iurienistor** [comment]
For now I recommend to use kits instead of single instrument per instance. First, every instance creates 16 output stereo channel. Also, it takes memory. In the version 3.0 anyway I'll optimize and make some things to be shared between instances. With 20 seconds... one instance will take ~117MB. Because I want to expand the kit to more instruments, probably I'll make changes in to the core synth to synthesize directly into audio thread. It will take a little more CPU but almost at no memory cost. Also, moving synthesis into audio thread will open other features like velocity expression for synth parameters. I have arrived to conclusion that the sampler like synth for synthesis is not very good way.

**Comment by Tremeschin** [comment]
Problem is that I often pitch shift some samples by playing a higher note than using a plugin with automation, and I don't really like having many outputs from a single instance as I'm kinda scared of it breaking suddenly so I prefer to have one instance per channel per sample, also managing the midi regions on Ardour is a lot simpler because I have everything playing separate (this is the main reason I do that).

Any chance of a single kit mode for Geonkick or just not loading the other kits unless they are used? 117 MB RAM per instance will definitely be an issue for my past projects, not the end of the world though as I don't use thaat much of samples.

**Comment by iurienistor** [comment]
The current multichannel version it takes 22 MB per instance. In the version 3.0 I'll change the synth and it will not take this memory, only if there will be loaded samples and there will be a plugin version with only one channel, multi and single version. Thus, theoretically an instance of the the plugin with one channel that loads a sample from file (for max 20s) at 48000 sample rate would take max 3.6MB.
