### ISSUE TITLE
LV2 is installed in wrong path

### ISSUE THREAD

**Issue by magnetophon** [iurie-sw/geonkick#120]
When I install geonkick on NixOS, it ends up in ``$PREFIX/$PREFIX/lib/lv2``.
This might very well be a NixOS issue.

When I set ``CMAKE_INSTALL_LIBDIR`` to ``lib``, the plugin goes to the correct path: ``$PREFIX/lib/lv2``.

**Comment by iurienistor** [comment]
Hi! Thank you. I'll check this until the next release.

**Comment by magnetophon** [comment]
I just installed 2.3.8 and it has this same problem.

**Comment by iurienistor** [comment]
Hi! I haven't looked into this yet. Version 2.3.8  is just a critical bug fix.

**Comment by magnetophon** [comment]
Alright.
I *do* appreciate the fact that you do a release when there are critical bugs!

**Comment by KottV** [comment]
what if you run cmake with all prefixes:

cmake -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_INSTALL_LIBDIR=/usr/lib

?

**Comment by magnetophon** [comment]
I would assume that still works, why would it change anything?

Why do you ask?
Do you want me to test it?

**Comment by KottV** [comment]
Maybe I misread your issue. I haven't NixOS so I just guess it's cmake does something with default prefixes

**Comment by magnetophon** [comment]
@KottV Sorry, *I*\m the one misreading here.

I'm having some unrelated issues while actually trying to test this, but I'm pretty sure that if I do as you suggest, the libs will end up in ``/usr/usr/lib``

I'll report back when I managed to test.

**Comment by iurienistor** [comment]
For example, Debian/Ubuntu default values are set by CMake and their values are:

CMAKE_INSTALL_PREFIX: /usr/local
CMAKE_INSTALL_LIBDIR: lib

which means that the plugin will be installed at /usr/loca/lib/lv2 according to this

install(DIRECTORY ${GKICK_LV2_DIR}/geonkick.lv2 DESTINATION ${CMAKE_INSTALL_PREFIX}/${CMAKE_INSTALL_LIBDIR}/lv2)

If you end up with something like $PREFIX/$PREFIX/lib/lv2 and if by prefix you mean /usr/local than it means that CMAKE_INSTALL_LIBDIR default value is not set correctly by CMake because Geonkick CMake script is not touching CMAKE_INSTALL_LIBDIR. Thus, I don't see what I could fix here. You can add in the beginning of CMake to print variables 

message("CMAKE_INSTALL_PREFIX: ${CMAKE_INSTALL_PREFIX}")                                                              |
message("CMAKE_INSTALL_LIBDIR: ${CMAKE_INSTALL_LIBDIR}") 

and see what are their values.

**Comment by magnetophon** [comment]
@iurienistor I found out that, in NixOS, ``CMAKE_INSTALL_LIBDIR`` is indeed set to  ``${CMAKE_INSTALL_PREFIX}/lib``.

To find out if the problem is with NixOS, I searched for similar issues, and found [this comment](https://github.com/NixOS/nixpkgs/pull/82654#issuecomment-599218668), claiming that "it's documented to allow absolute paths".

I know nothing about cmake, and I had trouble interpreting the documentation that is linked in the above comment, but I thought I'd pass on the info so you can make up your own mind.

If NixOS is the only, or one of the only distros that use an absolute path for ``CMAKE_INSTALL_LIBDIR``, feel free to close this issue, as it is easy enough to work around.

**Comment by iurienistor** [comment]
Form this documentation https://cmake.org/cmake/help/v3.16/module/GNUInstallDirs.html CMAKE_INSTALL_LIBDIR is not absolute path. It suggests something like llib or lib64 or lib/<multiarch-tuple> on Debian. Ok, I'll close this issue, because I don't see how I can fix this from my part. Thank you.
