### ISSUE TITLE
Export to sfz

### ISSUE THREAD

**Issue by iurienistor** [iurie-sw/geonkick#132]
Because in the next version there will be layer to velocity range mapping than export the kit to sfz makes sense.

**Comment by unfa** [comment]
That is an amazing idea!

**Comment by paulfd** [comment]
I have thought about implementing this in Geonkick for some time. Do you think about exporting the samples as wav files ? Maybe not everything, but sfz can also describe synthetized sounds. sfizz might not be too far off being able to reproduce a Geonkick sound given the recipe.

**Comment by iurienistor** [comment]
@paulfd yes, the plan is to export the sfz file along wave samples needed for SFZ file. 

"sfizz might not be too far off being able to reproduce a Geonkick sound given the recipe"... what do you mean?... what kind of reciple?

**Comment by iurienistor** [comment]
Implementing to export at this moment to sfz would be very easy. The instruments buffers are in the memory, they just need to be copied into files. But it would mean that regions will contain only one sample for all velocity range. I don't know if this is useful for percussion. In version 3.0 there is plan to add 4-6 layers for every instrument that will map to velocity ranges. In that case exporting to sfz will make sense. Now every instrument has 3 layers they are mixed in one buffer at the end, and can't be generated separately.

**Comment by paulfd** [comment]
Something like this

![Screenshot from 2020-10-27 16-49-14](https://user-images.githubusercontent.com/15227713/97326533-6124b280-1874-11eb-8d70-a3f79a120350.png)

could be expressed in sfz linguo as
```
<region> sample=*noise 
    eg1_ampeg=1
    eg1_time1=0    eg1_level1=1  
    eg1_time2=0.03 eg1_level2=0.6
    eg1_time3=0.06 eg1_level3=0.3
    eg1_time4=0.12 eg1_level4=0.1
    eg1_time5=0.3  eg1_level5=0  
    eg1_sustain=5
```

`eg` is the envelope, targeting the main amplitude envelope in this case. This is what I meant by recipe, but the implementation is not complete nor totally tested so it can be longer term. Doing this also means no sidecar files at all, since everything is generated on the fly.

**Comment by paulfd** [comment]
Short term exporting with wav is probably safer, I can try it once the velocity layers are in :slightly_smiling_face:
