### ISSUE TITLE
Problem Compiling in Fedora 32

### ISSUE THREAD

**Issue by JRSV** [iurie-sw/geonkick#143]
Hello, 

I am having problems compiling the software, I think I have installed all dependencies, including redkite. But I get the following when compiling

`/home/jrsv/geonkick/src/geonkick_button.cpp: In member function ‘void GeonkickButton::setPressedImage(const RkImage&)’:
/home/jrsv/geonkick/src/geonkick_button.cpp:34:33: error: ‘RkButton::ButtonImage’ has not been declared
   34 |         setImage(img, RkButton::ButtonImage::ImagePressed);
      |                                 ^~~~~~~~~~~
/home/jrsv/geonkick/src/geonkick_button.cpp: In member function ‘void GeonkickButton::setUnpressedImage(const RkImage&)’:
/home/jrsv/geonkick/src/geonkick_button.cpp:39:33: error: ‘RkButton::ButtonImage’ has not been declared
   39 |         setImage(img, RkButton::ButtonImage::ImageUnpressed);
      |                                 ^~~~~~~~~~~
make[2]: *** [CMakeFiles/geonkick_common_single.dir/build.make:1061: CMakeFiles/geonkick_common_single.dir/src/geonkick_button.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:228: CMakeFiles/geonkick_common_single.dir/all] Error 2
make: *** [Makefile:150: all] Error 2
`

any help you can give will be deeply apreciated

**Comment by quadrillionth** [comment]
Hi JRSV,

Looks like you're having the same issue I had: we both (probably) used the incorrect branch to build from.

Try this:
- clean everything (redkite and geonkick).
- download and build these instead:
https://github.com/iurie-sw/redkite/releases/tag/v1.2.0
https://github.com/iurie-sw/geonkick/releases/tag/v2.5.0

Note:
On my system (Mint Debian) I had one more error while building Geonkick regarding "setprecision". It was fixed by adding (without quotes) "#include < iomanip >" (remove the spaces in front of/after the word iomanip) into the GeonkickConfig.cpp file in the src directory. You can use this page as an example of where to place the #include bit if needed: https://github.com/iurie-sw/geonkick/blob/master/src/GeonkickConfig.cpp

An aside:
If you're going to run geonkick as a plug-in in ardour, you may need to copy the geonkick.lv2 folder from /usr/local/lib/lv2/ into /usr/lib/lv2/. Not sure if this will be necessary on Fedora.

I wont be helpful beyond this point. I am not a developer, had help (thanks again!) getting around the build errors and these are only my notes.

**Comment by iurienistor** [comment]
Hi! Yes, there is a need to use the release 1.2.0 for Redkite, not from master. I jut released a fix for Geonkick regarding setprecision: https://github.com/iurie-sw/geonkick/releases/tag/v2.5.1.
@quadrillionth Thank you for your help :)
