### ISSUE TITLE
VST3 Presets don't produce sound when playing MIDI

### ISSUE THREAD

**Issue by tank-trax** [iurie-sw/geonkick#68]
OS: Debian Buster 10.3

built Geonkick locally

Some presets are not working in Bitwig and Reaper

BartBrouns and magnetophons do not produce sound even when trying Any
the TimeKit presets work but have very low audio

When loading Geonkick the init works in Both Bitwig and Reaper when using MIDI
Also finding the same issue with the Standalone

Pressing the Green Arrow does produce sound, seems like it's not getting the MIDI signals

Am I doing something wrong?

If I create a preset using Geonkick with Bitwig and open it with Reaper and vice versa there is MIDI

**Comment by tank-trax** [comment]
Same thing happens with LV2 in jalv.select and Qtractor so appears to be something with the Presets

Perhaps they were created with an older version of Geonkick?

**Comment by iurienistor** [comment]
@tank-trax I've just built the the last version from github and tested the presets in Reaper (trial version) and for me it works (I think they are loud, since on default  it triggers on master not less than -6db). Geonkick has 16 channels, be sure that they are directed in Reaper because every preset has its own channel. 

"Same thing happens with LV2 in jalv.select and Qtractor so appears to be something with the Presets"... something do you mean the percussion graph is not shown? There may be some old presets, and you'll need to adjust the filters Q factor but as far as I remember I have updated all the presets.

"Pressing the Green Arrow does produce sound, seems like it's not getting the MIDI signals"... play arrow do not generate any MIDI signals, it is purely internal to Geonkick that triggers playing. if you hit play arrow, and you don't hear sound but at the same time see that the Geonkick limiter leveler shows something it means that the audio output of Geonkick is not directed correctly.

If you click play arrow and If limiter leveler don't show anything and you see percussion graph, than it means that the jack is not running (for standalone), for plugin this scenario practically can't happen of limiter is set correctly and the output channels are directed correctly too.

**Comment by iurienistor** [comment]
Just tested also in Bitwig.  Presets are working, their loudness level are close to default master limiter level. There is a need to direct all channels correctly for percussions. Also, for a reason Bitwig  sends all midi keys with an octave lower.

**Comment by tank-trax** [comment]
Thanks for the explanation. I realize now that output audio channels have to be set accordingly. Easier to do in Reaper and still haven't figured out how in Bitwig but it's working now

Is the standalone only supposed to have one input for midi and one output for audio?

**Comment by iurienistor** [comment]
> Is the standalone only supposed to have one input for midi and one output for audio?

Yes, but I think I need to add 16 channels. There is also was an idea to discontinue the standalone version, but maybe is still in demand.

**Comment by iurienistor** [comment]
Added this issue for 16 channels for standalone - https://github.com/iurie-sw/geonkick/issues/71
