### ISSUE TITLE
Feature request: snap frequency nodes to note?

### ISSUE THREAD

**Issue by elcalenx** [iurie-sw/geonkick#78]
Something that would be handy for quickly tuning sounds would be if frequency nodes snapped to nearby musical notes. (I believe this is something Sonic Academy's Kick 2 does.)

It's not too hard to get it in the right ballpark with the current tools, but it does feel like I have to always fiddle a while with the frequency whenever I move a node. Snapping would make it faster.

**Comment by iurienistor** [comment]
The notes shown are a little delusive. The problem is that this is restricted by the graphics resolution. With this I mean that when the frequency is mapped to pixels there will be frequencies that can't be shown between pixels. For example, if 1000Hz is mapped on 100pixel height there will be 10Hz per pixel. Thus, the notes associated don't show exact frequency of the note, but the close region that belong to that note. Sometimes depending of the frequency range selected, a note frequency can be selected exactly since it happened to be exact in one of the pixel.
I don't know I succeeded to explain the problem. I don't know other software handle this (probably they just don't specify this issue), but at least myself I don't see a real solution to this.

Snapping can be done but this will be only in background, UI will move the node just as close as possible to the exact note frequency and show the exact note frequency. But this mode of operation must be optional, and I don't know this will not be more confusing.

**Comment by magnetophon** [comment]
> Snapping can be done but this will be only in background, UI will move the node just as close as possible to the exact note frequency and show the exact note frequency. But this mode of operation must be optional, and I don't know this will not be more confusing.

I also think snapping would be great to have.
Most people won't realize there is a pixel/frequency problem in the first place, so I don't think snapping will confuse them.  Maybe I misunderstood.
