### ISSUE TITLE
Allow UI scaling to better support Hi-DPI 

### ISSUE THREAD

**Issue by jmaibaum** [iurie-sw/geonkick#96]
On Hi-DPI displays the Geonkick UI looks tiny:

![Bildschirmfoto von 2020-06-28 13-26-10](https://user-images.githubusercontent.com/3957164/85946263-914e5a00-b943-11ea-99dc-852954327107.png)

Would it be possible to add an in-plugin option for UI scaling, like, for example Robin Gareus does in https://x42-plugins.com/x42/x42-eq?

**Comment by iurienistor** [comment]
Hi! Unfortunately, in order to support this there is a need a lot of changes in the Geonkick UI. Text rendered by the graphics engine would be simpler to scale, but there are a lot of raw images that need to be scaled too (a copy of images per scale factor to avoid pixelation), and changes in the code to make this to work. I don't know If I'll start to implement this soon.

**Comment by iurienistor** [comment]
More discussion about this here: https://gitlab.com/iurie-sw/geonkick/-/issues/159
