### ISSUE TITLE
Improve documentation

### ISSUE THREAD

**Issue by iurienistor** [iurie-sw/geonkick#97]
@mxmilkiib Hi! I am not a native English speaker. I've seen you contributing to LV2 wiki. Would you like to contribute to Geonkick documentation with a review? :) Here is the documentation: https://github.com/iurie-sw/geonkick/blob/master/doc/Documentation.md

**Comment by mxmilkiib** [comment]
I'd be up for this by using the wiki rather than editing the file locally or via it's own web interface. The content can be transferred back to the file after, whether it's kept on the wiki after that can be up to you :)

**Comment by iurienistor** [comment]
Hi! Thank you. Here I have created the wiki page. Is it ok? :) - https://github.com/iurie-sw/geonkick/wiki/Geonkick-Documentation

**Comment by mxmilkiib** [comment]
That is good, thank you, though I don't have the ability to edit it currently. IMO, it's probably worth just having it set to open, at least for now, in-case anyone else has a related link, note or correction to add.

**Comment by iurienistor** [comment]
Please, try now, I have opened it. I hope it works for you.

**Comment by iurienistor** [comment]
Hi! Thank you for the contribution. I'll update the documentation from the wiki, but also I'll add other info about the new features.

**Comment by mxmilkiib** [comment]
I've finally found the time to fully go through the document again. I've made various further changes to the second half of the text to smooth out the grammar and reduce some of the repetition, but I've still not spent much time using the plugin yet, so I call on the mighty @unfa to make the request that, if they have the time and interest, could they possibly also have a look through the documentation text on the wiki to fix any wording that could be better altered to more accurately describe the operation of Geonkick? There's probably also room for a few more grammar/style tweaks that I either missed or passed by because I wasn't sure on how to phrase things (and I guess one last job would be to update the menu outline at the top).

**Comment by mxmilkiib** [comment]
(also, n.b.; I cheekily linked to an offsite image, but it'd be easy enough to paste an updated screenshot in this thread and then use that image GH url to replace the current documentation screenshot url, or something like that)

**Comment by iurienistor** [comment]
Hi! Thank you for the update. I'll merge the updates into the current doc of the release, and than I'll update back the wiki with the new added features. I think just review of some English grammar will be enough because for know probably only me know how things really works, especially in the new version. :)
