### ISSUE TITLE
Allow to build (lv2) without installing Redkite

### ISSUE THREAD

**Issue by x42** [iurie-sw/geonkick#99]
It would be nice if Redkite could be localized. for example as git submodule, or using a relative path to geokick's source tree.

Something like

```
cmake -DREDKITE_SOURCE=../redkite
LV2DIR=$HOME/.lv2  make install_lv2
```

So far I managed to do this:
```
git clone git@github.com:iurie-sw/redkite.git
mkdir redkite/build
cd redkite/build
cmake ..
make
make install DESTDIR=/tmp/rk/
mkdir /tmp/rk/usr/local/lib/
# fixup install path usr/lib/ -> usr/local/lib
mv /tmp/rk/usr/lib/libredkite.a /tmp/rk/usr/local/lib/libredkite.a
cd ../..
git clone git@github.com:iurie-sw/geonkick.git
mkdir geonkick/build
cd geonkick/build
# hack since geon does not support -CMAKE_LINKER_FLAGS, nor use REDKITE_SDK_PATH for libs and binary:
cmake .. -DGKICK_REDKITE_SDK_PATH=/tmp/rk/usr/local/ -DCMAKE_CXX_FLAGS="-L /tmp/rk/usr/local/lib/"
PATH=$PATH:/tmp/rk/usr/local/bin/ make
make install
mv -vi /tmp/gk/usr/local/lib/lv2/geonkick.lv2 ~/.lv2/
```

**Comment by iurienistor** [comment]
Hi! Probably you mean to install Redkite at a custom path. To do this there is

For  Redkite this will install Rekdite at /tmp/rk

    cmake -DCMAKE_INSTALL_PREFIX=/tmp/rk -DCMAKE_INSTALL_LIBDIR=lib  ..

For building after that Geonkick

    cmake -DGKICK_REDKITE_SDK_PATH=/tmp/rk -DCMAKE_INSTALL_PREFIX=/home/iurie/.lv2/ ..

But the only thing I've forgot to add for Geonkick in the CMakeList.txt is
link_directories(${REDKITE_LIBRARY_DIR}) because for custom Redkite install the linker will not find the library (unless the path to lib is set to the environment library variable)

Also, when installing Geonkick there an option to pass a custom data dir cmake -DGEONKICK_DATA_DIR... by default this is /home/usr/.local/share

Also, there is an option to pass CMAKE_INSTALL_FULL_DATADIR ... that will tell where to install presets, default is cmake will use CMAKE_INSTALL_PREFIX/share/

I need to make a fix here to add link_directories(${REDKITE_LIBRARY_DIR}) for the linker

And I'll update README to add all this info. Thank you for pointing to this!

**Comment by x42** [comment]
>  Probably you mean to install Redkite at a custom path

I do not want to install it at all.  It is only needed to compile the LV2 plugin, and after the plugin is linked, there is no need to keep redkite around anymore.

**Comment by x42** [comment]
> CMAKE_INSTALL_FULL_DATADIR ... that will tell where to install presets

I am not interested in the application, I only wanted the LV2 plugin. I assume the presets are bundled with the plugin since it must not depend on an external resources.

**Comment by iurienistor** [comment]
"I do not want to install it at all"

Ah, ok :) After Redkite build there is a need Geonkick to set all paths from REDKITE_SOURCE in order to built correctly. I'll think about this.

**Comment by iurienistor** [comment]
"I assume the presets are bundled with the plugin since it must not depend on an external resources."

No, they are not bundled. By default presets are installed at CMAKE_INSTALL_FULL_DATADIR in JSON format.

**Comment by iurienistor** [comment]
I'll introduce REDKITE_SOURCE in v2.3

**Comment by iurienistor** [comment]
Unfortuantely, I'll have leave this for the next release.

**Comment by iurienistor** [comment]
Implemented. Now Redkite is embedded into Geonkick source code and build.
